export const REFRESH_TOKEN: string = 'tRefreshToken';
export const ACCESS_TOKEN: string = 'tAccessToken';
export const SETTING_STORAGE_KEY: string = "TSettings";

export const experimentalText = " Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae sunt consectetur culpa saepe minima, facere voluptas fugit eius sequi, incidunt, soluta delectus accusantium aut? Atque aut iure repudiandae. Minima, distinctio.Quibusdam expedita consequuntur eaque autem laboriosam eum ex iste, dolorum recusandae doloribus inventore quas praesentium, dolor odio ? Quasi illum, recusandae porro fugit at dolorem omnis.Blanditiis praesentium quidem vitae odit. Officiis ea quisquam saepe.Doloribus accusamus cum, delectus dolorem illo eveniet nihil aliquam ? Cum, harum obcaecati nemo earum quo cupiditate voluptates qui maiores soluta consectetur ratione officiis laudantium eligendi dolores ? Accusamus iusto alias pariatur itaque quia deleniti! Nobis, laboriosam molestias necessitatibus, cum quisquam vero corrupti neque at, officiis voluptatibus sequi magnam delectus ? Quibusdam illo quaerat, magnam dolorem mollitia id aut! Necessitatibus cumque, similique et numquam sequi perspiciatis deserunt ea sit excepturi illum quae architecto minima rem explicabo, nobis enim! Numquam est voluptatem voluptate placeat officia unde, aliquid pariatur dignissimos alias ? Corporis harum ab a temporibus cum dignissimos quas, quam hic asperiores aperiam qui voluptate aut ex, recusandae repudiandae! Veritatis at officia itaque sapiente facere vero, similique nisi ullam temporibus voluptates ? Aliquam nostrum magnam ipsam tenetur consectetur quae.Eveniet iste voluptate consequatur quis, similique debitis doloribus! Nostrum facere optio omnis tenetur magni non, quisquam ipsa nobis atque accusamus, perspiciatis facilis porro. Delectus fuga harum id molestiae quisquam.A suscipit eveniet repudiandae id nulla est reiciendis excepturi maiores corrupti recusandae dolores minus cumque delectus voluptas, architecto adipisci ea similique aut nostrum explicabo. Incidunt perferendis pariatur amet voluptates eveniet laboriosam illum, et natus ducimus laudantium asperiores quam sint exercitationem aliquam, ea voluptate molestias nobis modi recusandae, vero placeat ? Labore minima delectus quod! Corrupti! Delectus sunt enim tempore porro ducimus! Voluptatum repellat nihil, aperiam repellendus quasi sit perspiciatis sapiente quod dolorum culpa optio tempore quam omnis dolores quia aliquam illo, fuga atque maiores sequi.";

export const ROLES = {
    MANGER: "manager",
    CUSTOMER: "customer",
    EMPLOYEE: "employee",
    ADMIN: "admin"
}

