# Generated by Django 5.0.4 on 2025-02-04 21:58

import cars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_reservation_car_remove_reservation_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.IntegerField()),
                ('is_available_daily', models.BooleanField(default=True)),
                ('is_available_monthly', models.BooleanField(default=False)),
                ('is_available_yearly', models.BooleanField(default=False)),
                ('daily_rent_price', models.FloatField()),
                ('monthly_rent_price', models.FloatField()),
                ('yearly_rent_price', models.FloatField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to=cars.models.PathAndRename('media/cars'))),
                ('image2', models.ImageField(blank=True, null=True, upload_to=cars.models.PathAndRename('media/cars'))),
                ('image3', models.ImageField(blank=True, null=True, upload_to=cars.models.PathAndRename('media/cars'))),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type_reservation', models.IntegerField()),
                ('status_reservation', models.IntegerField()),
                ('time_reservation', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
