# Generated by Django 5.0.4 on 2025-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.IntegerField(choices=[(1, 'فاخرة'), (2, 'اقتصادية'), (3, 'منشوف شو لسا في أنواع')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت'), (3, 'محجوزة')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت'), (3, 'محجوزة')]),
        ),
    ]
