# Generated by Django 3.2.25 on 2025-02-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت'), (3, 'محجوزة'), (4, 'منتهية الصلاحية')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_reservation',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت'), (3, 'محجوزة'), (4, 'منتهية الصلاحية')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.IntegerField(choices=[(1, 'يومي'), (2, 'شهري'), (3, 'سنوي')]),
        ),
    ]
