# Generated by Django 3.2.25 on 2025-05-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cars', '0004_alter_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id_office', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف المكتب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المكتب')),
                ('location', models.CharField(max_length=255, verbose_name='موقع المكتب')),
                ('phone_number_1', models.CharField(max_length=20, verbose_name='رقم التواصل 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل 2')),
            ],
            options={
                'verbose_name': 'مكتب',
                'verbose_name_plural': 'المكاتب',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='هل متاحة للبيع'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_owned_by_customer', to='users.customer', verbose_name='صاحب السيارة (زبون)'),
        ),
        migrations.AddField(
            model_name='car',
            name='sale_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر البيع'),
        ),
        migrations.CreateModel(
            name='OfficeAccount',
            fields=[
                ('id_office_account', models.AutoField(primary_key=True, serialize=False, verbose_name='معرّف السجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.office', verbose_name='معرف المكتب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='معرف الحساب')),
            ],
            options={
                'verbose_name': 'حساب مكتب',
                'verbose_name_plural': 'حسابات المكاتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner_office',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_owned_by_office', to='cars.office', verbose_name='صاحب السيارة (مكتب)'),
        ),
    ]
