# Generated by Django 3.2.25 on 2025-05-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0005_auto_20250515_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='officeaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='officeaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معرف الحساب'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.IntegerField(choices=[(1, 'يومي'), (2, 'شهري'), (3, 'سنوي'), (4, 'شراء')]),
        ),
    ]
