# Generated by Django 3.2.25 on 2025-05-16 00:21

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20250515_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cars.models.PathAndRename('image_office')),
        ),
        migrations.AddField(
            model_name='office',
            name='status_office',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_owned_by_office', to='cars.office', verbose_name='صاحب السيارة (مكتب)'),
        ),
    ]
