# Generated by Django 3.2.25 on 2025-05-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_account_type'),
        ('cars', '0007_auto_20250516_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='ratings',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfficeRating',
            fields=[
                ('id_office_rating', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.office', verbose_name='المكتب')),
            ],
            options={
                'unique_together': {('customer', 'office')},
            },
        ),
    ]
