# Generated by Django 3.2.25 on 2025-05-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20250516_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id_car_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع السيارة')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت'), (3, 'محجوزة'), (4, 'منتهية الصلاحية'), (5, 'مباعة')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_reservation',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت'), (3, 'محجوزة'), (4, 'منتهية الصلاحية'), (5, 'مباعة')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcategory'),
        ),
    ]
