# Generated by Django 3.2.25 on 2025-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20250516_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(choices=[(1, 'متاحة'), (2, 'حجز مؤقت للأجار'), (3, 'محجوزة للأجار'), (4, 'حجز مؤقت للبيع'), (5, 'منتهي الصلاحية'), (6, 'مباعة')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_reservation',
            field=models.IntegerField(choices=[(1, 'حجز مؤقت'), (2, 'حجز مؤكد'), (3, 'حجز منتهي الصلاحية')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.IntegerField(choices=[(1, 'أجار يومي'), (2, 'أجار شهري'), (3, 'أجار سنوي'), (4, 'شراء')]),
        ),
    ]
