# Generated by Django 3.2.25 on 2025-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20250521_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
