# Generated by Django 5.0.4 on 2025-02-04 17:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.PathAndRename('media/cars')),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.PathAndRename('media/cars')),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.PathAndRename('media/cars')),
        ),
        migrations.AlterField(
            model_name='customer',
            name='driving_license_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.PathAndRename('media/driving_license_image')),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.PathAndRename('media/id_back_image')),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.PathAndRename('media/id_front_image')),
        ),
    ]
