# Generated by Django 3.2.25 on 2025-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'مدير'), ('manager', 'مدير'), ('employee', 'موظف'), ('customer', 'زبون')], max_length=20),
        ),
    ]
