# Generated by Django 3.2.25 on 2025-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'أدمن'), ('manager', 'مدير'), ('employee', 'موظف'), ('customer', 'زبون')], max_length=20),
        ),
    ]
