# Generated by Django 5.0.4 on 2025-02-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_car_image1_alter_car_image2_alter_car_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
