import AuthGuard from "@/lib/guards/auth-guard";
import RoleGuard from "@/lib/guards/role-guard";
import AppProvider from "@/lib/providers";
import { Backgrounds, TextPrimary } from "@/lib/ui/class/classNames";
import clsx from "clsx";
import type { Metadata } from "next";
import AdminLayout from "../components/layout/admin/AdminLayout";
import NavLinks from "../components/layout/commonLayout/NavLinks";
import MobileNavMenu from "../components/layout/mobile/MobileNavMenu";
import { ROLES } from "../constants";
import "../globals.css";
import { employeeLinks } from "./employee/config";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={clsx(Backgrounds, TextPrimary, "scroll-smooth h-[100vh]")}>
        <>
          <span id="CardBackgrounds" className="bg-background-card-light dark:bg-background-card-dark size-0"></span>

          <span id="CardBackgroundsReverse" className="bg-background-card-dark dark:bg-background-card-light size-0"></span>

          <span id="Backgrounds" className="bg-background-default-light dark:bg-background-default-dark size-0"></span>

          <span id="TextPrimary" className="text-text-light-primary dark:text-text-dark-primary size-0"></span>

          <span id="TextPrimaryReverse" className="text-text-dark-primary dark:text-text-light-primary size-0"></span>

          <span id="TextSecondary" className="text-text-light-secondary dark:text-text-dark-secondary size-0"></span>

          <span id="BorderPrimary" className="border-text-light-primary dark:border-text-dark-primary size-0"></span>

          <span id="BorderSecondary" className="border-text-light-secondary dark:border-text-dark-secondary size-0"></span>

          <span id="shadowPrimary" className="shadow-background-default-dark dark:shadow-background-default-light"></span>
          <span id="shadowSecondary" className="shadow-background-card-dark dark:shadow-background-card-light"></span>
        </>
        <AppProvider>
          <AuthGuard>
            <RoleGuard
              roles={[ROLES.EMPLOYEE]}
            >
              <AdminLayout
                MenuLink={employeeLinks}
                navLinks={
                  <section>
                    <div
                      className="hidden lg:block"
                    >
                      <NavLinks />
                    </div>
                    <div
                      className="lg:hidden"
                    >
                      <MobileNavMenu />
                    </div>
                  </section>
                }
              >
                {children}
              </AdminLayout>
            </RoleGuard>
          </AuthGuard>
        </AppProvider>
      </body>
    </html>
  );
}
